import type { Metadata } from "next";

import "@/app/globals.css";
import { inter } from "@/app/ui/fonts";
import Sidebar from "@/app/ui/Sidebar";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.className} antialiased`}>
				<div className="flex flex-col md:flex-row md:overflow-hidden">
					<div className="w-full h-screen flex-none md:w-64">
						<Sidebar />
					</div>
					<div className="flex-grow p-6 md:overflow-y-auto md:p-12">
						{children}
					</div>
				</div>
			</body>
		</html>
	);
}
